//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblToken
    {
        public int IdToken { get; set; }
        public string Token { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Ip { get; set; }
        public Nullable<int> fkIdUsuario { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Descripcion { get; set; }
    }
}
